# Generated by Django 4.2.1 on 2023-07-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
