# Generated by Django 3.2.15 on 2023-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
