# Generated by Django 4.2.1 on 2023-07-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
