# Generated by Django 4.2.1 on 2023-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0009_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
